[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
exclude = "^(test-postgres-data|postgres-data|__pycache__)/"

[tool.coverage.run]
omit = [
    "**/logging_service.py",
    "**/logging_middleware.py",
    "**/db_init.py",
    "**/models/__init__.py"
]
